import { DomainError, RoomBriefSchema, assertProjectTransition, estimateQuantities, totalQuantities, type CatalogKey, type ProposalLine, type Role } from "@/domain/obria";
import { buildOpportunity, DEMO_CLIENT_ID, DEMO_PROJECT_ID, DEMO_SUPPLIER_ID, loadState, record, type DemoState } from "@/server/demo-store";
import { getMediaProvider } from "@/server/providers/media-provider";

export type Actor = { id: string; role: Role; scope?: string[] };
export function authorizeAction(actor: Actor, role: Role, action: string, projectId = DEMO_PROJECT_ID) { if (actor.role !== role) throw new DomainError("FORBIDDEN", `Ação ${action} exige papel ${role}`, 403); if (projectId !== DEMO_PROJECT_ID) throw new DomainError("NOT_FOUND", "Projeto não encontrado", 404); }
function state() { return loadState(); }
export async function createProject(actor: Actor, briefInput: unknown) { authorizeAction(actor, "CLIENT", "createProject"); const brief = RoomBriefSchema.parse(briefInput); const db = state(); db.project.brief = brief; db.project.state = "DRAFT"; db.project.revision += 1; record(db, "PROJECT_CREATED", actor.id); return db.project; }
export async function analyzeAndCreateDesign(actor: Actor, projectId = DEMO_PROJECT_ID, prompt?: string) { authorizeAction(actor, "CLIENT", "createDesign", projectId); const db = state(); if (db.project.state === "PLAN_APPROVED" || db.project.state === "READY_TO_SHARE" || db.project.state === "OPEN_FOR_QUOTES") throw new DomainError("PLAN_LOCKED", "A versão aprovada bloqueia novas iterações"); assertProjectTransition(db.project.state, "DESIGNING"); db.project.state = "DESIGNING"; record(db, "DESIGN_REQUESTED", actor.id); const iteration = db.versions.length + 1; const provider = getMediaProvider(); const job = await provider.createDesign({ brief: db.project.brief, iteration, prompt, currentImageDataUri: db.versions.at(-1)?.imageDataUri }); const quantities = estimateQuantities(db.project.brief, job.plan.interventions.map((item) => item.catalogKey)); const version = { id: `version-demo-${iteration}`, projectId, number: iteration, state: "READY" as const, summary: job.plan.summary, plan: job.plan, imageDataUri: job.imageDataUri, quantities, costCents: totalQuantities(quantities), co2Grams: 82_000 - iteration * 1_500, createdAt: process.env.DEMO_CLOCK ?? "2026-08-19T12:00:00.000Z" }; db.versions = db.versions.map((item) => item.state === "READY" ? { ...item, state: "SUPERSEDED" as const } : item); db.versions.push(version); db.project.analysis = await provider.analyzeRoom(db.project.brief); db.project.state = "DESIGN_READY"; db.project.revision += 1; record(db, "DESIGN_READY", actor.id); return version; }
export function approveDesign(actor: Actor, projectId: string, versionId: string, expectedRevision: number) { authorizeAction(actor, "CLIENT", "approveDesign", projectId); const db = state(); if (db.project.revision !== expectedRevision) throw new DomainError("REVISION_CONFLICT", "A sala mudou; atualize antes de aprovar", 409); if (db.project.state !== "DESIGN_READY") throw new DomainError("INVALID_STATE", "Apenas uma versão pronta pode ser aprovada"); const version = db.versions.find((item) => item.id === versionId); if (!version) throw new DomainError("NOT_FOUND", "Versão não encontrada", 404); assertProjectTransition(db.project.state, "PLAN_APPROVED"); version.state = "APPROVED"; db.project.approvedVersionId = versionId; db.project.state = "PLAN_APPROVED"; db.project.revision += 1; record(db, "DESIGN_APPROVED", actor.id); return { project: db.project, version }; }
export function publishOpportunity(actor: Actor, projectId = DEMO_PROJECT_ID) { authorizeAction(actor, "CLIENT", "publishOpportunity", projectId); const db = state(); if (db.project.state !== "PLAN_APPROVED" && db.project.state !== "READY_TO_SHARE") throw new DomainError("INVALID_STATE", "Aprove o plano antes de publicar"); db.opportunity = buildOpportunity(db); db.project.state = "OPEN_FOR_QUOTES"; db.project.revision += 1; record(db, "OPPORTUNITY_PUBLISHED", actor.id); return db.opportunity; }
export function listOpportunities(actor: Actor) { authorizeAction(actor, "SUPPLIER", "listOpportunities"); const db = state(); return db.opportunity ? [{ ...db.opportunity, imageDataUri: db.opportunity.imageDataUri }] : []; }
export function createProposal(actor: Actor, opportunityId: string, input: { lines: ProposalLine[]; freightCents: number; taxCents: number; leadDays: number; validUntil: string; includes: string[]; excludes: string[] }) { authorizeAction(actor, "SUPPLIER", "createProposal"); const db = state(); if (!db.opportunity || db.opportunity.id !== opportunityId) throw new DomainError("NOT_FOUND", "Oportunidade não encontrada", 404); const totalCents = input.lines.reduce((sum, line) => sum + line.priceCents, 0) + input.freightCents + input.taxCents; const proposal = { id: "proposal-demo-001", opportunityId, supplierId: actor.id, state: "SUBMITTED" as const, ...input, totalCents }; db.proposals = [proposal]; db.opportunity.status = "AWAITING_ACCEPTANCE"; db.project.state = "AWAITING_ACCEPTANCE"; record(db, "PROPOSAL_SUBMITTED", actor.id); return proposal; }
export function acceptProposal(actor: Actor, proposalId: string) { authorizeAction(actor, "CLIENT", "acceptProposal"); const db = state(); const proposal = db.proposals.find((item) => item.id === proposalId); if (!proposal) throw new DomainError("NOT_FOUND", "Proposta não encontrada", 404); if (proposal.state === "ACCEPTED") return proposal; if (db.project.state !== "AWAITING_ACCEPTANCE") throw new DomainError("INVALID_STATE", "Não há proposta aguardando aceite"); proposal.state = "ACCEPTED"; if (db.opportunity) db.opportunity.status = "ACCEPTED"; db.project.state = "ACCEPTED"; record(db, "PROPOSAL_ACCEPTED", actor.id); return proposal; }
export function demoActor(role: Role): Actor { return role === "CLIENT" ? { id: DEMO_CLIENT_ID, role, scope: ["client:read", "client:write"] } : { id: DEMO_SUPPLIER_ID, role, scope: ["supplier:read", "supplier:write"] }; }
export function getDemoView(actor: Actor): DemoState { if (actor.role === "SUPPLIER") { const db = state(); return { ...db, project: { ...db.project, originalAsset: "redacted", analysis: { observed: [], uncertainties: [], fixedElements: [] } }, versions: db.versions.filter((version) => version.state === "APPROVED"), }; } return state(); }
